### PR TITLE
Convert the action type from docker to composite

### LINKED ISSUE #3: Switch to composite actions?
As far as I can see, there's nothing here that requires containers, so why not simplify it, increasing the compatibility matrix along the way?

### PR DESCRIPTION
**Pull request by webknjaz**
Previously, this action was using Docker containers as its runtime. It has a number of drawbacks, namely:

  * each workflow using the action, wastes resources building a fresh container from the `Dockerfile`;

  * `docker` actions only work on GNU/Linux runners and wouldn't be usable by the end-users running it as a part of a job matrix.

This patch converts the only meaningful configuration step to use a `composite` action interface, which is not as resource-hungry and runner-agnostic.

Resolves #3

### CODE REVIEW

**Comment by webknjaz** [comment]
@AA-Turner why did you go for `sh`? Isn't bash advertised as available on all platforms?

**Comment by webknjaz** [comment]
@AA-Turner could you cut the release? The last tag is 4 years old.

**Comment by AA-Turner** [comment]
To match the dockerfile more exactly, as it specified ``sh``. If there's a benefit to using bash, happy to switch.

A

**Comment by AA-Turner** [comment]
> @AA-Turner could you cut the release? The last tag is 4 years old.

Done

**Pull request merged**
